from db import get_session, Customer
from sqlalchemy.exc import SQLAlchemyError


def add_customer(customer_name: str, customer_address: str):
    """Add a new customer. customer_id is auto-generated by the DB."""
    session = get_session()
    try:
        customer = Customer(customer_name=customer_name, customer_address=customer_address)
        session.add(customer)
        session.commit()
        session.refresh(customer)
        print(f"Customer added with ID: {customer.customer_id}")
        return customer
    except SQLAlchemyError as e:
        session.rollback()
        print(f"Error adding customer: {e}")
    finally:
        session.close()


def get_customer(customer_id: int):
    """Fetch a customer by ID."""
    session = get_session()
    try:
        customer = session.get(Customer, customer_id)
        if not customer:
            print(f"No customer found with ID: {customer_id}")
        return customer
    except SQLAlchemyError as e:
        print(f"Error fetching customer: {e}")
    finally:
        session.close()


def update_customer(customer_id: int, new_name: str = None, new_address: str = None):
    """Update a customer's name and/or address by ID."""
    session = get_session()
    try:
        customer = session.get(Customer, customer_id)
        if not customer:
            print(f"No customer found with ID: {customer_id}")
            return None
        if new_name:
            customer.customer_name = new_name
        if new_address:
            customer.customer_address = new_address
        session.commit()
        session.refresh(customer)
        return customer
    except SQLAlchemyError as e:
        session.rollback()
        print(f"Error updating customer: {e}")
    finally:
        session.close()


def delete_customer(customer_id: int):
    """Delete a customer by ID."""
    session = get_session()
    try:
        customer = session.get(Customer, customer_id)
        if not customer:
            print(f"No customer found with ID: {customer_id}")
            return False
        session.delete(customer)
        session.commit()
        print(f"Customer {customer_id} deleted.")
        return True
    except SQLAlchemyError as e:
        session.rollback()
        print(f"Error deleting customer: {e}")
    finally:
        session.close()