from db import get_session, Warehouse
from sqlalchemy.exc import SQLAlchemyError


def add_warehouse(warehouse_address: str, warehouse_name: str = None):
    '''Add a new warehouse. warehouse_id is auto-generated by the DB'''
    session = get_session()
    try:
        warehouse = Warehouse(warehouse_address=warehouse_address, warehouse_name=warehouse_name)
        session.add(warehouse)
        session.commit()
        session.refresh(warehouse)
        print(f'Warehouse added with ID: {warehouse.warehouse_id}')
        return warehouse
    except SQLAlchemyError as e:
        session.rollback()
        print(f'Error adding warehouse: {e}')
    finally:
        session.close()


def get_warehouse(warehouse_id: int):
    """Fetch a warehouse by ID."""
    session = get_session()
    try:
        warehouse = session.get(Warehouse, warehouse_id)
        if not warehouse:
            print(f"No warehouse found with ID: {warehouse_id}")
        return warehouse
    except SQLAlchemyError as e:
        print(f"Error fetching warehouse: {e}")
    finally:
        session.close()


def update_warehouse(warehouse_id: int, new_warehouse_address: str = None, new_warehouse_name: str = None):
    '''Update the address or name for a warehouse'''
    session = get_session()
    try:
        warehouse = session.get(Warehouse, warehouse_id)
        if not warehouse:
            print(f"No warehouse found with ID: {warehouse_id}")
        if new_warehouse_address:
            warehouse.warehouse_address = new_warehouse_address
        if new_warehouse_name:
            warehouse.warehouse_name = new_warehouse_name
        session.commit()
        session.refresh(warehouse)
        return warehouse
    except SQLAlchemyError as e:
        session.rollback()
        print(f'Error updating warehouse: {e}')
    finally:
        session.close()


def delete_warehouse(warehouse_id: int):
    session = get_session()
    try:
        warehouse = session.get(Warehouse, warehouse_id)
        if not warehouse:
            print(f"No warehouse found with ID: {warehouse_id}")
        session.delete(warehouse)
        session.commit()
        print('Deleted warehouse with ID: {warehouse_id}')
        return True
    except SQLAlchemyError as e:
        session.rollback()
        print(f'Error deleting warehouse: {e}')
    finally:
        session.close()
