services:
  api:
    build: services/api-gateway/
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # RabbitMQ Messaging Port
      - "15672:15672" # RabbitMQ Management UI Port

  worker:
    build: services/worker
    env_file:
      - .env
    command: celery -A app.worker worker --loglevel=info
    depends_on: 
      - rabbitmq
      - db
volumes:
  postgres_data:
      